### ISSUE TITLE
Division in python  throws an unexpected result

### ISSUE THREAD

**Issue by hakS07** [Calysto/calysto_scheme#29]
i'm trying to write a simple python code for arithmetic operation 
`x=int(c[1])/320
print(c)
print(c[1],round(x,2))`
######
c=['S1069L03.jpg', '178', '142', '102', '\n']
(c[1],round(x.2))=('178', 0.0)
#####
**### the result is false because 178/320=0.55**
does anyone have an idea how i can resolve it

**Comment by dsblank** [comment]
Where are you using Python code? This is the issue tracker for Calysto Scheme.
