### ISSUE TITLE
README.md is not in the pip package

### ISSUE THREAD

**Issue by joearasin** [Calysto/calysto_scheme#3]
When I `pip3 install --upgrade calysto-scheme`, the installation fails with:

```
File "/private/var/folders/xb/5q674_3x6kl7v8vczp17p6gr0000gn/T/pip-build-3b37q2b2/calysto-scheme/setup.py", line 49, in <module>
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

I downloaded calysto_scheme-0.8.2.tar.gz manually, and untarred the output:

```
tar -xvzf calysto_scheme-0.8.2.tar.gz 
x calysto_scheme-0.8.2/
x calysto_scheme-0.8.2/setup.py
x calysto_scheme-0.8.2/calysto_scheme/
x calysto_scheme-0.8.2/calysto_scheme/scheme.py
x calysto_scheme-0.8.2/calysto_scheme/__init__.py
x calysto_scheme-0.8.2/calysto_scheme/kernel.py
x calysto_scheme-0.8.2/calysto_scheme/__main__.py
x calysto_scheme-0.8.2/PKG-INFO
```

So the file isn't making it into the build.

Checking out the git repo and doing `python setup.py install` works fine.

**Comment by ratulotron** [comment]
Facing the same problem. Will try installing from the repo.

**Comment by dsblank** [comment]
Thanks! Working on a new method of installing...

**Comment by blink1073** [comment]
@dsblank, you need a MANIFEST.in file: https://github.com/Calysto/metakernel/blob/master/MANIFEST.in

**Comment by dsblank** [comment]
Yes, at least that. But I have been looking at your fixes to metakernel
setup.py... but maybe that's all I need...

**Comment by dsblank** [comment]
Attempt to fix pushed and uploaded to pypi, using MANIFEST.in. Please try.
