### ISSUE TITLE
Docker image doesn't work anymore

### ISSUE THREAD

**Issue by gchamon** [Calysto/calysto_scheme#30]
Image `jupyter/notebook` doesn't exist anymore, so I took the liberty to create another image from `nbgallery/jupyter-alpine` (https://github.com/nbgallery/jupyter-alpine).

The alpine based image is supposed to be minimal. The final image is ~407MB.

The dockerfile is as follows:

```
FROM nbgallery/jupyter-alpine

RUN mkdir /app
WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade jupyter
RUN pip3 install --upgrade notebook

RUN pip3 install --upgrade calysto-scheme
RUN python3 -m calysto_scheme install

CMD jupyter notebook --allow-root --ip=0.0.0.0 --port=80
```

It can be downloaded from my Docker hub as `gchamon/calysto-scheme-alpine:latest` and run as `docker run -it -p 8888:80 -v $(pwd):/app gchamon/calysto-scheme-alpine`

Feel free to use the Dockerfile at will!

Thanks for the kernel! It is helping me a lot with SICP

**Comment by dsblank** [comment]
Cool, and thanks for sharing!

**Comment by dsblank** [comment]
Updated Dockerfile and README.md. Thank you!
