### ISSUE TITLE
scheme option is not available

### ISSUE THREAD

**Issue by Ravi3p4** [Calysto/calysto_scheme#31]

**Comment by Ravi3p4** [comment]
Scheme option not available on jupyter notebook

**Comment by dsblank** [comment]
You'll have to provide more details. Did you install it as per the instructions? What kind of environment are you running?

**Comment by Ravi3p4** [comment]
Jupiter notebook has already installed on my system, but to debug my code I
am unable to see scheme option can you please tell me how I can get the
scheme option on same application.

BR,
Raviraj

**Comment by dsblank** [comment]
```
python -m pip install calysto-scheme
python -m calysto_scheme install
```

is all that is required.
