### ISSUE TITLE
Error Running Calysto Scheme notebook

### ISSUE THREAD

**Issue by asmodehn** [Calysto/calysto_scheme#32]
While running the Calysto Scheme Language notebook (from master), I encountered this error :
```
(symbol "apple")

Traceback (most recent call last):
  File "In [177]", line 1, col 2
RunTimeError: unbound variable 'symbol'

```

I ll try to investigate as far as I can, but do people who know Calysto Scheme have any hint ?

**Comment by dsblank** [comment]
Is that the only error you get? Other things are working ok?

**Comment by dsblank** [comment]
Actually, looking at what is defined, I see that "symbol" has not been defined yet. Would you like to try to add it?

**Comment by dsblank** [comment]
Actually actually, Calysto Scheme spells that command `string->symbol`

**Comment by dsblank** [comment]
Command-completion works very well to see what is defined. And `(dir)` lists all variables and macros.

**Comment by asmodehn** [comment]
Thanks, simpler problem than I thought : symbol => string->symbol
I'm discovering Calysto and just trying things out... This was the first obvious error I could find.

**Comment by asmodehn** [comment]
In hte same notebook, this cell also fails : 
`((get 'test 'verify) "test-name" 1 = 1)`

And that one and related get-attr (not sure what is expected ?)
`(import "conx")`
