### ISSUE TITLE
what does caaar mean? 

### ISSUE THREAD

**Issue by schwinge** [Calysto/calysto_scheme#37]
https://github.com/Calysto/calysto_scheme/search?q=caaar
got a hard time reading caadar caaddr caadr caar cadaar cadadr cadar caddar cadddr in the tutorial
can anyone explain this?

**Comment by dsblank** [comment]
`(caar item)` is short for `(car (car item))` and (cadar item) is short for `(car (cdr (car item)))` You see the pattern?
