### ISSUE TITLE
Any interest in Dockerizing?

### ISSUE THREAD

**Issue by joearasin** [Calysto/calysto_scheme#4]
I threw together a quick Dockerfile that spins up a Jupyter notebook with Calysto Scheme.

https://github.com/joearasin/docker-jupyter-scheme

Not sure if you've used Docker at all, but it means that, with Docker setup, one line in the shell will spin up a notebook running Calysto scheme. It's useful in the context of "it'd be nice to have a notebook to work through SICP with".

`docker run -d -p 8888:8888 -v `pwd`:/notebooks joearasin/jupyter-scheme`

Anyway, I was wondering if you had any interest in making it "official".

**Comment by dsblank** [comment]
Oh, cool! Thank you so much for this... I've been trying to wrap my head around Docker to do exactly this. Yes, let's make it official! What do we need to do?

**Comment by joearasin** [comment]
Not 100% sure, but I think the best way to do this is create a "calysto" account on dockerhub, link it to github, and, add the dockerfile to this repo and set it up as an autobuild on dockerhub. It should autobuild images then.

**Comment by dsblank** [comment]
I'll try to look into that tonight.

**Comment by dsblank** [comment]
Now published as calysto/calysto_scheme at dockerhub. Thanks! I'm going to add more languages, and perhaps a master docker that has all of the metakernel/calysto languages (maybe more).

**Comment by joearasin** [comment]
Awesome!  🍻
