### ISSUE TITLE
Question regarding named parameters

### ISSUE THREAD

**Issue by bentxt** [Calysto/calysto_scheme#40]
Hi,

Is there a way to call (Python) host functions with named parameters like in this

```
import subprocess
process = subprocess.Popen(['echo', 'More output'],
                     stdout=subprocess.PIPE, 
                     stderr=subprocess.PIPE)
```

Calysto is great and I would like to use it more for everyday scripting.
Thanks, 
Ben

**Comment by dsblank** [comment]
Thanks @bentxt ! We started to add named-parameters, but got bogged down in some details. We have a nice implementation of dictionaries now, and got rid of the "association" abstraction. Would you be interested in working on a PR to add them?

**Comment by dsblank** [comment]
BTW, named parameters now work when calling Python function from Scheme. It is a bit hacky until we have specific syntax. Currently, if the last argument to a Python function is a dictionary, then it is assumed to be a dict of kwargs. We'll have to fix that someday to make it more robust.

**Comment by dsblank** [comment]
Just to clarify, you can do what you wish (in general):

```
(import "subprocess")
(define process (subprocess.Popen 
     '("echo" "More output")
      (dict '((stdout : subprocess.PIPE)
              (stderr : subprocess.PIPE)))))
```

I'm not sure though about the details of subprocess inside Calysto Scheme.
