### ISSUE TITLE
about useing python's libs

### ISSUE THREAD

**Issue by hsz1273327** [Calysto/calysto_scheme#5]
Excuse me... i want to use  `random` in calysto_scheme .But I find that I don't know how to use a python lib in it......can you give me some structions ?

**Comment by dsblank** [comment]
Sure!

```
In [1]: (import "random")
Out[1]: (random)

In [2]: (random.random)
Out[2]: 0.5360263663557511
```

**Comment by hsz1273327** [comment]
thanks

来自 魅蓝 note 2

-------- 原始邮件 --------
发件人：Doug Blank notifications@github.com
时间：周五 4月29日 上午 09:13
收件人：Calysto/calysto_scheme calysto_scheme@noreply.github.com
抄送：HUANG SIZHE hsz1273327@gmail.com,Author author@noreply.github.com
主题：Re: [Calysto/calysto_scheme] about useing python's libs (#5)
