### ISSUE TITLE
Lexical address is wrong for local-defines

### ISSUE THREAD

**Issue by arlindohall** [Calysto/calysto_scheme#8]
I've been using Calysto to learn Scheme using the exercises from SICP in a Jupyter notebook. While running one of my examples, I noticed that it was failing where before it had passed. I believe that this is because the first time I ran the code, the function `good-enough?` was only defined in the local scope, while the second time I had just re-run all of the code in the notebook, causing it to be defined externally. 

My code is located here: https://github.com/arlindohall/sicp/blob/master/Chapter1.ipynb

According to what I've learned so far, this should cause the local definition to be used, but Calysto used the global definition. I think this is the case, because the error I got was: 
```
Traceback (most recent call last):
  File "In [7]", line 16, col 1, in 'sqrt'
  File "In [7]", line 14, col 3, in 'sqrt-iter'
  File "In [5]", line 2, col 7, in 'good-enough?'
  File "In [5]", line 14, col 11, in '-'
UnhandledException: unsupported operand type(s) for -: 'float' and 'NoneType'
```
and the global definition of `good-enough?` has two arguments, while the local one only has one argument.

Steps to reproduce:
1. Open New Jupyter Notebook
2. Enter the following in separate code blocks
```
(define (sqrt x)
  (define (square y)
    (* y y))
  (define (average a b)
    (/ (+ a b) 2))
  (define (good-enough? guess)
    (< (abs (- (square guess) x)) 0.001))
  (define (improve guess)
    (average guess (/ x guess)))
  (define (sqrt-iter guess)
    (if (good-enough? guess)
        guess
        (sqrt-iter (improve guess))))
  (sqrt-iter 1.0))
```
```
(sqrt 9)
```
```
(define (abs x)
  (if (< x 0)
      (- x)
      x))
(define (square x) (* x x))
(define (good-enough? guess x)
  (< (abs (- (square guess) x)) 0.001))
```
```
(define (sqrt x)
  (define (square y)
    (* y y))
  (define (average a b)
    (/ (+ a b) 2))
  (define (good-enough? guess)
    (< (abs (- (square guess) x)) 0.001))
  (define (improve guess)
    (average guess (/ x guess)))
  (define (sqrt-iter guess)
    (if (good-enough? guess)
        guess
        (sqrt-iter (improve guess))))
  (sqrt-iter 1.0))
```
```
(sqrt 9)
```
3. Run in order, produces the following:
```
Traceback (most recent call last):
  File "In [5]", line 1, col 1, in 'sqrt'
  File "In [4]", line 14, col 3, in 'sqrt-iter'
  File "In [4]", line 11, col 9, in 'good-enough?'
  File "In [3]", line 7, col 11, in '-'
UnhandledException: unsupported operand type(s) for -: 'float' and 'NoneType'
```

Behavior in GNU Scheme:
```
1 ]=> (define (sqrt x)
  (define (square y)
    (* y y))
  (define (average a b)
    (/ (+ a b) 2))
  (define (good-enough? guess)
    (< (abs (- (square guess) x)) 0.001))
  (define (improve guess)
    (average guess (/ x guess)))
  (define (sqrt-iter guess)
    (if (good-enough? guess)
        guess
        (sqrt-iter (improve guess))))
  (sqrt-iter 1.0))

;Value: sqrt

1 ]=> (sqrt 9)

;Value: 3.00009155413138

1 ]=> (define (abs x)
  (if (< x 0)
      (- x)
      x))
(define (square x) (* x x))
(define (good-enough? guess x)
  (< (abs (- (square guess) x)) 0.001))
;Value: abs

1 ]=>
;Value: square

1 ]=> (define (sqrt x)
  (define (square y)
    (* y y))
  (define (average a b)
    (/ (+ a b) 2))
  (define (good-enough? guess)
    (< (abs (- (square guess) x)) 0.001))
  (define (improve guess)
    (average guess (/ x guess)))
  (define (sqrt-iter guess)
    (if (good-enough? guess)
        guess
        (sqrt-iter (improve guess))))
  (sqrt-iter 1.0))
;Value: good-enough?

1 ]=> (sqrt 9)

;Value: sqrt

1 ]=>
;Value: 3.00009155413138
```

<img width="863" alt="screen shot 2017-12-29 at 1 10 14 am" src="https://user-images.githubusercontent.com/5963070/34430827-fc8ae0c2-ec36-11e7-963c-165a67163239.png">
<img width="891" alt="screen shot 2017-12-29 at 1 11 29 am" src="https://user-images.githubusercontent.com/5963070/34430838-0c050082-ec37-11e7-9845-b0ae1caea7aa.png">
<img width="1170" alt="screen shot 2017-12-29 at 1 12 04 am" src="https://user-images.githubusercontent.com/5963070/34430840-105a9796-ec37-11e7-9ffd-5016c3dd91cc.png">
<img width="1152" alt="screen shot 2017-12-29 at 1 12 22 am" src="https://user-images.githubusercontent.com/5963070/34430842-12853382-ec37-11e7-9585-b08911f4c998.png">

**Comment by dsblank** [comment]
Thanks for trying Calysto Scheme, and for reporting this issue!

I'm not sure what is causing this. You might be able to help diagnose the issue because Calysto Scheme is written in Scheme. I think the relevant code is here:

Where "define" is handled:

https://github.com/Calysto/calysto_scheme/blob/master/calysto_scheme/src/interpreter-cps.ss#L477-L481

Where "lookup-binding-in-first-frame" is defined here:

https://github.com/Calysto/calysto_scheme/blob/master/calysto_scheme/src/environments-cps.ss#L194-L203

Or, if you are a Python expert, you could insert some debugging code (`import pdb; pdb.set_trace()`) in the single Python file that is generated from the Scheme:

https://github.com/Calysto/calysto_scheme/blob/master/calysto_scheme/scheme.py

Perhaps @jmarshallgit has an idea, as he is the primary architect.

**Comment by dsblank** [comment]
The problem appears to be in our lexical address code. As a workaround you can turn it off, and then it will work:

```scheme
(use-lexical-address #f)
```
![screenshot from 2018-01-02 08-25-37](https://user-images.githubusercontent.com/168568/34485091-b67dc99c-ef96-11e7-9a24-da9823fce25c.png)

**Comment by arlindohall** [comment]
This work-around solves the issue in the immediate sense, thanks! I am still learning about scheme in my free time, but I will be glad to look into the code for lexical address once I get more of a feel for the language.

Thanks for your help - Calysto scheme is a really cool project!

**Comment by dsblank** [comment]
Thanks for your kind words! @jmarshallgit and I are planning to look at this issue over the next month or so.

**Comment by dsblank** [comment]
Talked to @jmarshallgit and he suggested having calysto scheme first put dummy defines into the current scope, and then lexical scope will find the correct place. Would need to be done wherever local defines can be made. (All of the defines at this level should be poked into scope first).
